### ISSUE TITLE
for help!

### ISSUE THREAD

**Issue by walkerjohnsonofficial** [melissagirl/PocketChipsChallenge#1]
Hello, I encountered some difficulties when making Chat-GPT bear, such as I couldn‘t install 64-bit python on raspberry pi, so azure-cognitiveservices-speech 1.38.0 couldn’t be used, and I couldn‘t go on. Could you send me a git hub project or other quick solutions to these problems? Thanks!

**Comment by auburncodingclub** [comment]
> Hello, I encountered some difficulties when making Chat-GPT bear, such as I couldn‘t install 64-bit python on raspberry pi, so azure-cognitiveservices-speech 1.38.0 couldn’t be used, and I couldn‘t go on. Could you send me a git hub project or other quick solutions to these problems? Thanks!

Hey, you have the wrong github project.

**Comment by walkerjohnsonofficial** [comment]
Yes, I have never known how to contact you. I have been stuck on some small
errors and failed to debug them successfully, but I don’t know where the
problem lies. Hope to get help from experts! Sorry for causing trouble to
you! !

Auburn Coding Club ***@***.***> 于2024年8月26日周一 23:09写道：

**Comment by makermelissa** [comment]
> Yes, I have never known how to contact you. I have been stuck on some small errors and failed to debug them successfully, but I don’t know where the problem lies. Hope to get help from experts! Sorry for causing trouble to you! ! Auburn Coding Club ***@***.***> 于2024年8月26日周一 23:09写道：

That project was one I worked on for Adafruit. Please post to forums.adafruit.com.

**Comment by walkerjohnsonofficial** [comment]
Thank you so much! I'll give it a try!

Melissa LeBlanc-Williams ***@***.***> 于2024年8月26日周一 23:19写道：
